runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/demo-ui-app/index.html
    upload: dist/demo-ui-app/index.html
  - url: /
    static_dir: dist/demo-ui-app

